name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  healthcheck:
    name: Health Check
    runs-on: ubuntu-24.04
    container:
      image: gradle:8.12.0-jdk21
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Health Check
        run: gradle clean test --tests 'DummyHealthCheckTest'

      - name: Upload HealthCheck Report
        uses: actions/upload-artifact@v4
        with:
          name: HealthCheck-ExtentReport
          path: build/reports/tests/test/index.html

  smoke:
    name: Smoke
    runs-on: ubuntu-24.04
    needs: healthcheck
    container:
      image: gradle:8.12.0-jdk21
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Smoke Test
        run: gradle clean test --tests 'ProductSmokeTest' --tests 'UserSmokeTest'

      - name: Upload Smoke Report
        uses: actions/upload-artifact@v4
        with:
          name: Smoke-ExtentReport
          path: build/reports/tests/test/index.html

  contract:
    name: Contract
    runs-on: ubuntu-24.04
    needs: smoke
    container:
      image: gradle:8.12.0-jdk21
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Contract Test
        run: gradle clean test --tests 'ProductContractTest' --tests 'UserContractTest'

      - name: Upload Contract Report
        uses: actions/upload-artifact@v4
        with:
          name: Contract-ExtentReport
          path: build/reports/tests/test/index.html

  functional:
    name: Functional
    runs-on: ubuntu-24.04
    needs: contract
    container:
      image: gradle:8.12.0-jdk21
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Functional Test
        run: gradle clean test --tests 'ProductFunctionalTest'

      - name: Upload Functional Report
        uses: actions/upload-artifact@v4
        with:
          name: Functional-ExtentReport
          path: build/reports/tests/test/index.html
